"use client";

import { useTransition } from "react";
import { useRouter } from "next/navigation";
import { Loader2Icon } from "lucide-react";

import {
  rebuildBlocksAction,
  setApprovalAction,
  createOutputAction,
  type ActionResult,
} from "@/app/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Field,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import type {
  Claim,
  ContentBlock,
  OutputRecord,
} from "@/lib/db/block-types";
import type { Asset } from "@/lib/db/types";
import { useActionState } from "react";
import Link from "next/link";

const initial: ActionResult | null = null;

export function AssemblyPanel({
  projectId,
  blocks,
  claims,
  assets,
  outputs,
}: {
  projectId: string;
  blocks: ContentBlock[];
  claims: Claim[];
  assets: Asset[];
  outputs: OutputRecord[];
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const createAction = createOutputAction.bind(null, projectId);
  const [createState, createFormAction, createPending] = useActionState(
    createAction,
    initial,
  );

  function rebuild() {
    startTransition(async () => {
      await rebuildBlocksAction(projectId);
      router.refresh();
    });
  }

  function approve(
    entity: "content_block" | "claim" | "asset" | "output",
    id: string,
    approval: "approved" | "rejected" | "draft",
  ) {
    startTransition(async () => {
      await setApprovalAction(projectId, entity, id, approval);
      router.refresh();
    });
  }

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardHeader>
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-col gap-1">
              <CardTitle>Content blocks</CardTitle>
              <CardDescription>
                Assembled from answers and assets — never regenerated by AI.
              </CardDescription>
            </div>
            <Button onClick={rebuild} disabled={pending}>
              {pending ? (
                <Loader2Icon data-icon="inline-start" className="animate-spin" />
              ) : null}
              Rebuild blocks
            </Button>
          </div>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          {blocks.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              Answer questions first, then rebuild to create reusable blocks.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Block</TableHead>
                  <TableHead>Preview</TableHead>
                  <TableHead>Approval</TableHead>
                  <TableHead className="text-right">Review</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {blocks.map((block) => (
                  <TableRow key={block.id}>
                    <TableCell className="font-medium">
                      {block.title || block.block_type}
                    </TableCell>
                    <TableCell className="max-w-md truncate text-muted-foreground">
                      {block.body.text || block.body.metric || "—"}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{block.approval}</Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={pending}
                          onClick={() =>
                            approve("content_block", block.id, "approved")
                          }
                        >
                          Approve
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          disabled={pending}
                          onClick={() =>
                            approve("content_block", block.id, "rejected")
                          }
                        >
                          Reject
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Claims & evidence</CardTitle>
          <CardDescription>
            Public metrics require approval. Unsupported claims stay out of
            exports.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {claims.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No claims yet. Measurable outcomes create draft claims during
              rebuild.
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Claim</TableHead>
                  <TableHead>Approval</TableHead>
                  <TableHead className="text-right">Review</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {claims.map((claim) => (
                  <TableRow key={claim.id}>
                    <TableCell>{claim.claim_text}</TableCell>
                    <TableCell>
                      <Badge variant="outline">{claim.approval}</Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={pending}
                          onClick={() => approve("claim", claim.id, "approved")}
                        >
                          Approve
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          disabled={pending}
                          onClick={() => approve("claim", claim.id, "rejected")}
                        >
                          Reject
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Asset approval</CardTitle>
          <CardDescription>
            Blocked or unapproved assets cannot ship in public outputs.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {assets.length === 0 ? (
            <p className="text-sm text-muted-foreground">No assets yet.</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Asset</TableHead>
                  <TableHead>Permission</TableHead>
                  <TableHead>Approval</TableHead>
                  <TableHead className="text-right">Review</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {assets.map((asset) => (
                  <TableRow key={asset.id}>
                    <TableCell>{asset.title}</TableCell>
                    <TableCell>
                      <Badge variant="secondary">{asset.permission}</Badge>
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline">{asset.approval}</Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="outline"
                        disabled={pending || asset.permission === "blocked"}
                        onClick={() => approve("asset", asset.id, "approved")}
                      >
                        Approve
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Outputs</CardTitle>
          <CardDescription>
            Assemble approved blocks only — website, LinkedIn, Upwork, or PDF.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-6">
          <form action={createFormAction} className="flex flex-col gap-4">
            <FieldGroup>
              <Field>
                <FieldLabel htmlFor="output_type">Output type</FieldLabel>
                <select
                  id="output_type"
                  name="output_type"
                  required
                  className="h-8 w-full max-w-sm rounded-lg border border-input bg-transparent px-2.5 text-sm outline-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50"
                >
                  <option value="website">Website case study</option>
                  <option value="linkedin_carousel">LinkedIn carousel</option>
                  <option value="linkedin_post">LinkedIn post</option>
                  <option value="upwork">Upwork portfolio</option>
                  <option value="pdf">PDF presentation</option>
                </select>
              </Field>
            </FieldGroup>
            {createState?.ok === false && createState.error ? (
              <p className="text-sm text-destructive" role="alert">
                {createState.error}
              </p>
            ) : null}
            <Button type="submit" disabled={createPending || pending}>
              {createPending ? (
                <Loader2Icon data-icon="inline-start" className="animate-spin" />
              ) : null}
              Assemble output
            </Button>
          </form>

          {outputs.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Type</TableHead>
                  <TableHead>Approval</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Open</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {outputs.map((output) => (
                  <TableRow key={output.id}>
                    <TableCell>{output.output_type}</TableCell>
                    <TableCell>
                      <Badge variant="outline">{output.approval}</Badge>
                    </TableCell>
                    <TableCell className="text-muted-foreground">
                      {new Date(output.created_at).toLocaleString()}
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="outline"
                        render={
                          <Link
                            href={`/projects/${projectId}/outputs/${output.id}`}
                          />
                        }
                        nativeButton={false}
                      >
                        View
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : null}
        </CardContent>
      </Card>
    </div>
  );
}
