import type { OutputPayload } from "@/lib/db/block-types";
import type { Asset } from "@/lib/db/types";

export interface HTMLGeneratorOptions {
  payload: OutputPayload;
  assets?: Asset[];
  projectName?: string;
  clientName?: string;
}

export function generateWebsiteHTML(options: HTMLGeneratorOptions): string {
  const { payload, assets = [], projectName, clientName } = options;
  const assetMap = new Map(assets.map((a) => [a.id, a]));

  const assetHTML = (assetIds?: string[]) => {
    if (!assetIds || assetIds.length === 0) return "";
    return assetIds
      .map((id) => {
        const asset = assetMap.get(id);
        if (!asset) return "";
        return `
          <div class="my-8">
            <img 
              src="${asset.storage_path || `/api/assets/${id}`}" 
              alt="${asset.title || "Project image"}"
              class="w-full rounded-lg shadow-lg"
            />
            ${asset.title ? `<p class="text-sm text-gray-500 mt-2 text-center">${asset.title}</p>` : ""}
          </div>
        `;
      })
      .join("");
  };

  const sectionsHTML = payload.sections
    .map(
      (section) => `
    <section class="mb-16">
      <h2 class="text-3xl font-bold mb-6 text-gray-900">${section.heading}</h2>
      <div class="prose prose-lg max-w-none">
        <p class="text-gray-700 leading-relaxed whitespace-pre-wrap">${section.body}</p>
      </div>
      ${assetHTML(section.asset_ids)}
    </section>
  `,
    )
    .join("");

  const warningsHTML =
    payload.warnings.length > 0
      ? `
    <!-- Warnings (visible in source, hidden from public view) -->
    <!--
    ${payload.warnings.map((w) => `  - ${w}`).join("\n")}
    -->
  `
      : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${payload.title}${clientName ? ` | ${clientName}` : ""}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    }
  </style>
</head>
<body class="bg-gradient-to-br from-gray-50 to-gray-100 min-h-screen">
  <div class="max-w-4xl mx-auto px-6 py-12">
    <!-- Header -->
    <header class="mb-16 text-center">
      ${clientName ? `<p class="text-sm uppercase tracking-wide text-gray-500 mb-2">${clientName}</p>` : ""}
      <h1 class="text-5xl font-extrabold text-gray-900 mb-4">
        ${payload.title}
      </h1>
      ${projectName ? `<p class="text-xl text-gray-600">${projectName}</p>` : ""}
    </header>

    <!-- Main Content -->
    <main>
      ${sectionsHTML}
    </main>

    <!-- Footer -->
    <footer class="mt-20 pt-8 border-t border-gray-200 text-center text-sm text-gray-500">
      <p>Generated by Phoenux Case Study Assembler</p>
      <p class="mt-2">© ${new Date().getFullYear()} All rights reserved</p>
    </footer>
  </div>

  ${warningsHTML}
</body>
</html>`;
}

export function generateLinkedInCarouselHTML(options: HTMLGeneratorOptions): string {
  const { payload } = options;
  const slides = payload.slides || payload.sections.slice(0, 12);

  const slidesHTML = slides
    .map((slide, index) => {
      const heading =
        "title" in slide && typeof slide.title === "string"
          ? slide.title
          : "heading" in slide
            ? slide.heading
            : "Slide";
      return `
    <div class="slide bg-white rounded-xl shadow-xl p-12 flex flex-col justify-center min-h-[600px]">
      <div class="slide-number text-sm font-bold text-blue-600 mb-4">${index + 1} / ${slides.length}</div>
      <h2 class="text-4xl font-bold mb-6 text-gray-900">${heading}</h2>
      <p class="text-xl text-gray-700 leading-relaxed whitespace-pre-wrap">${slide.body}</p>
    </div>
  `;
    })
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${payload.title} - LinkedIn Carousel</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
    .slide { width: 1080px; height: 1080px; }
  </style>
</head>
<body class="bg-gray-100 p-8">
  <div class="space-y-8">
    <div class="text-center mb-8">
      <h1 class="text-3xl font-bold mb-2">${payload.title}</h1>
      <p class="text-gray-600">LinkedIn Carousel Preview (1080x1080px per slide)</p>
    </div>
    ${slidesHTML}
  </div>
</body>
</html>`;
}

export function generateUpworkHTML(options: HTMLGeneratorOptions): string {
  const { payload, clientName } = options;

  const sectionsHTML = payload.sections
    .map(
      (section) => `
    <div class="mb-8">
      <h3 class="text-xl font-bold mb-3 text-gray-900">${section.heading}</h3>
      <p class="text-gray-700 leading-relaxed whitespace-pre-wrap">${section.body}</p>
    </div>
  `,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${payload.title} - Portfolio Entry</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white">
  <div class="max-w-3xl mx-auto px-6 py-8">
    <div class="mb-8">
      <h1 class="text-3xl font-bold mb-2 text-gray-900">${payload.title}</h1>
      ${clientName ? `<p class="text-gray-600">${clientName}</p>` : ""}
    </div>
    ${sectionsHTML}
  </div>
</body>
</html>`;
}
